global:
  scrape_interval: 1s
  scrape_timeout: 1s
  evaluation_interval: 15s
  external_labels:
    monitor: codelab-monitor
alerting:
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets: []

scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - localhost:9090
    - 34.207.153.229:9090

- job_name: node
  honor_timestamps: true
  scrape_interval: 5s
  scrape_timeout: 1s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - localhost:9100
    labels:
      group: production

- job_name: 'docker'
  static_configs:
  - targets: ['172.17.0.1:9323'] # metrics address from our daemon.json file
